### ISSUE TITLE
Tagged version

### ISSUE THREAD

**Issue by akerl** [mgechev/revive#100]
Howdy!

In https://github.com/mgechev/revive/issues/66 , it seems the determination was to tag releases w/o publishing release binaries. That said, it doesn't look like there's any tags as-yet.

I'm looking to use Revive in CI builds, where ideally I can lock the version of revive so that a given build is consistent. Right now, I'm locking to the git hash, but that's not ideal.

Is the intention to start tagging releases / provide a changelog, as per that issue?

**Comment by mgechev** [comment]
Let's close this in favor of https://github.com/mgechev/revive/issues/66
