### ISSUE TITLE
Rule `optimize-operands-order` reports potentially dangerous change when `len` of slice is used before slice accesing.

### ISSUE THREAD

**Issue by moukoublen** [mgechev/revive#1004]
**Describe the bug**
In this case:

```golang
if len(s) > 0 || s[0] == "" { // should not match, not safe
    // ...
}
```

Rule `optimize-operands-order` reports 

```plain
for better performance 'len(s) == 0 || s[0] == ""' might be rewritten as 's[0] == "" || len(s) == 0'
```

Which could lead to panic if implemented. 

**To Reproduce**
1. I updated revive `go install github.com/mgechev/revive@latest`
2. I run it with the following flags & configuration file:

```shell
# no extra flags
revive -config revive.toml .
```

```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.3
errorCode = 0
warningCode = 0

[rule.optimize-operands-order]
```

**Expected behavior**
I think in this case, where the `len` check is essential to happen before slice accessing, the rule should not match. 

**Additional context**
My first thought about fixing this was to not consider the built-in `len` function as a caller. 
I tried to change the `isCaller` function in the [optimize-operands-order.go](https://github.com/mgechev/revive/blob/0df1bb0860f7b25091b9227cccd45f69a28ab37a/rule/optimize-operands-order.go#L51) file so that it does not consider the built-in `len` function as a caller.

I opened a pr with this approach.

**Comment by ccoVeille** [comment]
@moukoublen thanks for identifying and fixed that

> Personally, I use this rule to lint my code while I'm coding thus I can decide if the suggested modification is safe or not.

@chavacava I agree with you, but some people are applying suggested changes blindly. It's great that @moukoublen introduced a safeguard
