### ISSUE TITLE
New release for Go 1.22 support?

### ISSUE THREAD

**Issue by jalaziz** [mgechev/revive#1013]
Sorry to be this guy, but any chance of a new release soon-ish?

We ran into some warnings related to the loop vars that should be silenced in Go 1.22, but the changes to silence the warnings are not in the latest release.

**Comment by denisvmedia** [comment]
I made a release today. I had to skip 1.3.8 as there was an issue with goreleaser. So, the new version is 1.3.9. Can you please check if it addresses your issues?

**Comment by jalaziz** [comment]
Confirmed it addresses the issue!

However, the changelog for 1.3.9 is missing all the changes since 1.3.7 (probably because of the skipped 1.3.8). Not sure if it's worth fixing, but just wanted to call it out.
