### ISSUE TITLE
var-naming enforce snake_case

### ISSUE THREAD

**Issue by sparshev** [mgechev/revive#1033]
**Is your feature request related to a problem? Please describe.**
My projects already using snake_case for local function variables and that will be great if I can configure revive var-naming to switch from camelCase to snake_case to follow the project style.

**Describe the solution you'd like**
I will try to prepare a simple change - that should not be that hard to flip the logic of verifier.

**Describe alternatives you've considered**
There is not much options available and none allows to enforce snake_case. For sure one style for all etc, but what to do with existing projects where the style is established and it's a huge political decision to change something...

**Additional context**

**Comment by chavacava** [comment]
Hi @sparshev, thanks for the proposal.
IMO `revive` should enforce Go idiomatic code. Using snake case is far to be standard in Go code-bases.

**Comment by sparshev** [comment]
Yeah, I see... Also checked if it's simple to add - nope, not that easy, especially because we need to split the var name into words and it's not that easy with camel case... So no luck...
