### ISSUE TITLE
Add option to enable all lints in the command line

### ISSUE THREAD

**Issue by andradei** [mgechev/revive#104]
**Is your feature request related to a problem? Please describe.**
Having to pass a `-config config.toml` without being able to simply `-all` to get all of the lint rules.

**Describe the solution you'd like**
Add a `-all` or something similar to the command line options so a TOML config file isn't needed.

**Comment by mgechev** [comment]
I'd prefer to not introduce new command line options and keep the interface minimalistic.

What are your main concerns with using a `config.toml` file?

**Comment by andradei** [comment]
One extra config file to keep around as opposed to an extra command-line option. This really comes down to preference and convenience. I understand your goal, feel free to close the issue if it doesn't follow it.

**Comment by mgechev** [comment]
Let's keep it open for now and collect opinions. If more folks would want to use `-all` flag we can enable it.

**Comment by chavacava** [comment]
The configuration file does not only contain the list of rules to apply but also some knobs that control `revive` behavior (default severity, error code to return, [...](https://github.com/mgechev/revive#configuration)) **and** the particular configurations of some rules like `argument-limit`, `cyclomatic`, `max-public-sctructs`, `line-length-limit`... 

Today those rules will panic if there is no configuration for them (for example try to use `line-length-limit` without setting its argument). We can set _defaults_ for rules' configuration values but, of course, they will be totally arbitrary thus not necessarily adapted to everyone's use cases.

To resume, if the goal is to _be able to run `revive` without a config file_ then I'm afraid is not just as simple as adding a `-all` flag to the command line.

**Comment by narqo** [comment]
This might be outside of the scope of the issue, but it would nice if revive allowed enable/disable particular rule via command line argument.

Since there is no one default name for the config file (i.e. `$PRJ_ROOT/.revive.toml`), it isn't clear how to configure an editor (vim+ale / vscode-go) use the same set of rules across different projects.

As an example `revive -rule.exported=off` would be the only thing I wanted to configure for my editor.

**Comment by andradei** [comment]
@akerl Yes. The only way to configure any of the lints is via config file.

**Comment by mgechev** [comment]
Let's keep the configurability as minimalistic as possible. Closing it for now. Feel free to comment for further discussion.
