### ISSUE TITLE
Add the receiver name length check to `rule.receiver-naming`

### ISSUE THREAD

**Issue by ytnsym** [mgechev/revive#1040]
**Is your feature request related to a problem? Please describe.**
I would like to check the length of receiver variable names.

**Describe the solution you'd like**
Add the receiver variable name length check to the `receiver-naming` rule.

**Describe alternatives you've considered**
I created a [linter](https://github.com/ytnsym/receivernamelen), but it seemed like it would be better to improve the `receiver-naming` rule.

**Additional context**
https://github.com/golangci/golangci-lint/pull/5007#issuecomment-2350457699

**Comment by chavacava** [comment]
Hi @ytnsym, thanks for the proposal.
Could you please check if the implementation proposed at the PR #1048 fits your expectations.
