### ISSUE TITLE
Ignore preexisting technical debt

### ISSUE THREAD

**Issue by floppyzedolfin** [mgechev/revive#109]
My project is rather big, and already has lots of warnings raised by revive. I am using git.
My goal is both to avoid creating new debt items, and to reduce current debt. However, "new debt items" are lost in the sea of "existing debt items", which makes them very difficult to spot.

Any of the following would help me identify new debt items:
- Dumping the results of my code at date t0, and use that file in revive to filter out preexisting bugs
Example: `revive -formatter friendly -config defaults.toml -ignore debt_19032019 src/... `
- Let revive remove items that were part of the parent branch (if it can find it) or already present at a given commit / tag.
Examples: `revive -formatter friendly -config defaults.toml -ignore origin/dev src/... `
`revive -formatter friendly -config defaults.toml -ignore c458fe3a src/... `

**Comment by mgechev** [comment]
@floppyzedolfin I'd suggest to achieve this as part of an external tool. For example, something like [this](https://dev.to/ohbarye/lint-only-over-changed-files-4e7j) or https://github.com/mgechev/revive/issues/42.
