### ISSUE TITLE
Revive `1.5.0` process hangs

### ISSUE THREAD

**Issue by cordis-dev** [mgechev/revive#1120]
**To Reproduce**
1. Download and extract https://github.com/mgechev/revive/releases/download/v1.5.0/revive_windows_amd64.tar.gz
2. Run it with the following flags & file:

```shell
revive.exe t.go
```
`t.go`
```go
func Test() {}
```

**Expected behavior**
Revive process should complete.

**Desktop**
 OS: Windows 11 23H2

**Comment by chavacava** [comment]
Hi @cordis-dev thanks for reporting the issue.
Right now I do not have access to a windows machine but on linux I was unable to reproduce the problem.
Could you please confirm that the input file contains exactly

```go
func Test() {}
```
(without `package` declaration)

**Comment by chavacava** [comment]
I've reproduced the problem on a windows machine.
