### ISSUE TITLE
Extending indent-error-flow to check for other branch statements

### ISSUE THREAD

**Issue by chavacava** [mgechev/revive#12]
The rule `indent-error-flow` checks if the `if`block ends with a `return` statement. The rule could also check for `if` blocks ending with branch statements like `continue`,`break`, or (ouch!) `goto`

[I've made the dev and I can make a pull request if you are interested]

Note: the rule is part of the `golint`-related rules, if the goal is to be isofunctional with golint then instead of extending the rule, a new one can be created.

**Comment by mgechev** [comment]
Hey @chavacava, yes, introducing a new rule will be great so we can keep the integrity of the inherited rules from golint.
