### ISSUE TITLE
Imports order

### ISSUE THREAD

**Issue by mapreal19** [mgechev/revive#125]
**Is your feature request related to a problem? Please describe.**
I'd like to see a clear order in imports between github packages, golang packages or custom packages

**Describe the solution you'd like**
Inspired by: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

The idea is to have a code like this as _valid_:

```go
import (
	"os"
	"strings"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"golang.org/x/crypto/bcrypt"

        "my-app/model"
)
```

While this would be _invalid_:
```go
import (
	"os"
	"strings"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"golang.org/x/crypto/bcrypt"
        "my-app/model"
)
```

**Additional context**
Thoughts? I think ensuring some order in imports would help.

**Comment by chavacava** [comment]
Hi @mapreal19, I'm currently facing this problem with my work's code base.
Some developers commit without ensuring correct formatting of their code (and that includes sorting imports with goimports)

**Comment by mapreal19** [comment]
@chavacava same here. How difficult would be difficult to detect local packages from 3rd party packages? I would include that separation for now and see if others like the rule.

**Comment by chavacava** [comment]
I think that the rule needs to be in sync with the imports formatting provided by standard tools; that way using, for example, `goimports` will ensure that the rule will not complain.
I do not know if standard formatting tools separate third-party imports from local ones.

**Comment by EricByers** [comment]
`goimports` has a `-local` flag that splits things up a bit more, but you have to provide the prefix.

https://github.com/golang/tools/blob/master/cmd/goimports/goimports.go#L50

**Comment by chavacava** [comment]
Thanks for the info @EricByers. So, the rule needs to accept a parameter equivalent to that of `goimports`  to be able to sync the behaviors of the rule and the formatter

**Comment by mapreal19** [comment]
Found later this: https://github.com/golang/go/wiki/CodeReviewComments#imports

> Imports are organized in groups, with blank lines between them. The standard library packages are always in the first group.

```go
package main

import (
	"fmt"
	"hash/adler32"
	"os"

	"appengine/foo"
	"appengine/user"

        "github.com/foo/bar"
	"rsc.io/goversion/version"
)
```

**Comment by mgechev** [comment]
This looks to be more of a formatting problem rather than linting. I'd suggest to keep it outside of the scope of revive for now.

**Comment by SamuelCabralCruz** [comment]
inspired from this gist: https://gist.github.com/soniah/c11633551c6dd84dab66cad20453cfa8 -> this is how I solved the problem: 
```
.PHONY: format
format:
	@find . -type f -name *.go | xargs -n 1 sed -i '' -e '/^import/,/^)/ { /^$$/ d; }'
	@goimports -w .
	@gofumpt -w -s .
```
