### ISSUE TITLE
Implement -set_exit_status

### ISSUE THREAD

**Issue by danielbprice** [mgechev/revive#15]
**Is your feature request related to a problem? Please describe.**

The problem is dropping this in as a replacement to `golint`.

**Describe the solution you'd like**

revive looks *very* close to being a drop-in replacement for golint, but support for the `-set_exit_status` flag that `golint` implements would really help.  We use this exit status to drive automation.
```
  -set_exit_status
        set exit status to 1 if any issues are found
```

**Comment by mgechev** [comment]
@danielbprice you can set the exit status in the config file https://github.com/mgechev/revive#configuration. You can:

```toml
# config.toml
severity = 'error'
errorCode = 1
```

```bash
revive -config config.toml 
```
