### ISSUE TITLE
Revive violates the Rule of Silence

### ISSUE THREAD

**Issue by markelog** [mgechev/revive#165]
When revive finds no errors it prints:

> 0 problems (0 errors) (0 warnings)

This violates the Rule of Silence:

> The rule of silence, also referred to as the silence is golden rule, is an important part of the Unix philosophy that states that when a program has nothing surprising, interesting or useful to say, it should say nothing. It means that well-behaved programs should treat their users' attention and concentration as being valuable and thus perform their tasks as unobtrusively as possible. That is, silence in itself is a virtue. (http://www.linfo.org/rule_of_silence.html)

What would you say to a PR that made revive silent by default?

**Comment by mgechev** [comment]
@markelog this seems valid for the friendly & the stylish formatters. Would you fix both?

**Comment by markelog** [comment]
Can do :)
