### ISSUE TITLE
Ability to provide a reason for rule disabling

### ISSUE THREAD

**Issue by jBugman** [mgechev/revive#190]
I would like the ability to provide a reason for rule disabling (on the same line) as an option. Adding anything to the `revive:` comment breaks it (regex I guess?), so currently I must do it on a separate line.

I propose two things:

1. Ability to write comments like
`// revive:disable-line:RULE   This is intentional`
or even (for cleaner integration with other tools)
//  revive:disable:var-naming   TODO: fix it later

2. Global config flag (disabled by default) that would require to provide the reason (like `staticcheck` does by default)

**Comment by mgechev** [comment]
This makes sense. I'll look at it over the weekend. If anyone has bandwidth to take it before that please comment here.

**Comment by chavacava** [comment]
Hi, I've proposed something similar last year (see #73) 
I'll try to create a PR this weekend.

**Comment by chavacava** [comment]
I have a first running version without the config flag.
Suggestions for the name of this flag?

**Comment by mgechev** [comment]
`specifyDisableReason` maybe. It's a bit long but expresses well what it's all about. Open to other suggestions!
