### ISSUE TITLE
config file discovery

### ISSUE THREAD

**Issue by delfick** [mgechev/revive#235]
**Is your feature request related to a problem? Please describe.**
I want to be able to run revive from my text editor without having to make my text editor find revive.toml to use.

**Describe the solution you'd like**
Have revive look up directories until it finds a revive.toml rather than only looking in home.

**Describe alternatives you've considered**
I can make vim find a revive.toml to use, but I'd rather rely on revive itself for that.

**Comment by mgechev** [comment]
My concern would be for systems where the file look up is expensive (for example, at Google we're using one). This may delay the initial start of revive a lot depending on how deeply nested is the current working directory.

**Comment by delfick** [comment]
perhaps introduce a cli argument to disable config discovery?

I imagine for most people, file lookup isn't expensive.

**Comment by mgechev** [comment]
>I can make vim find a revive.toml to use, but I'd rather rely on revive itself for that.

Maybe that's good enough? I'm trying to keep the configuration minimalistic and do not introduce any further configuration options/logic when it could be achieved with external tools.

I'll keep the issue open in case this is a pain that many people want to resolve.

**Comment by chavacava** [comment]
Another concern with auto discovery is that you do not know precisely which configuration you are actually using (if you known which conf you are "auto discovering" then why not just point it explicitly?)

**Comment by delfick** [comment]
But it already finds a config in a home directory, which means developers can get different results from revive on their different computers based on whether they have one in home directory or not, whereas if one is in the repository, then they will have consistent results if they just say revive.

I'd also argue that auto finding configuration by looking up folders is a common pattern and less surprising than it not doing that.

**Comment by mgechev** [comment]
>But it already finds a config in a home directory, which means developers can get different results from revive on their different computers based on whether they have one in home directory or not, whereas if one is in the repository, then they will have consistent results if they just say revive.

I'm more leaning towards dropping this feature.

>I'd also argue that auto finding configuration by looking up folders is a common pattern and less surprising than it not doing that.

This is more common for dynamic languages, I'd say. In Node.js it's a common practice. I'm not confident it's a good one.

**Comment by mgechev** [comment]
Let's close this feature request for now and revisit if it's in a higher demand.
