### ISSUE TITLE
Inheriting rules from default.toml

### ISSUE THREAD

**Issue by delfick** [mgechev/revive#236]
**Is your feature request related to a problem? Please describe.**
When I define my own revive.toml, it seems to disable all the rules. It'd be great if I could just tell it to use the rules from default.toml (with perhaps ability to turn off specific rules) so I don't have to change my config when revive adds new rules, but still have options like what error codes to return with.

**Comment by mgechev** [comment]
It's not obvious what `default.toml` is without looking at the source code. Knowing it's what golint provides, is good enough for running `revive` without a config, but doesn't provide sufficient information on what would be the effect of the overrides.

I'd prefer if we keep this outside of the scope of the project, but let's collect more opinions.

**Comment by chavacava** [comment]
The particularities of each code base and the software quality policies of each dev team makes me think that running revive with an unknown configuration (default.toml) is not without risk. For example new rules can produce a large number of "unimportant" failures or, the contrary, inadvertently skip some "important" checks.

Also notice that, usually, new rules are not added to the default configuration.

**Comment by mgechev** [comment]
@chavacava this makes sense. Let's close for now, we can revisit at a later stage.
