### ISSUE TITLE
fish/osx problems?

### ISSUE THREAD

**Issue by tommyjcarpenter** [mgechev/revive#239]
I'm running fish shell on mac 10.14.6 

**Describe the bug**
After installing this tool using the instructions, I cannot run it
```
 ~  go get -u github.com/mgechev/revive     
 ~  revive                                                                                                                                                                     
    fish: Unknown command revive
```

This is slightly suspect as the go get command returns without an error however it also prints no stdout

**To Reproduce**
1. I updated revive `go get -u github.com/mgechev/revive`
2. I run it with the following flags & configuration file:

**Expected behavior**
it runs

Is there a homebrew package for this?

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Version of Go

**Additional context**

**Comment by mgechev** [comment]
What's the value of `$GOPATH`? Did you add `$GOPATH/bin` to your `$PATH`?

**Comment by tommyjcarpenter** [comment]
doh! $GOPATH/bin was not in $PATH, thanks for your quick help, and thanks for your work here, can't wait to give it a try!
