### ISSUE TITLE
Is it possible for revive to return a non-zero exit code when there are issues and zero if not?

### ISSUE THREAD

**Issue by inliquid** [mgechev/revive#241]
I'd like to run `revive` in some sort of automated test during build. However I found that it returns zero in any case. This makes it more complicated to check result of running the tool.

**Comment by chavacava** [comment]
Hi @inliquid, in the configuration you can set 

```
# Sets the error code for failures with severity "error"
errorCode = 0
# Sets the error code for failures with severity "warning"
warningCode = 0
```
to the values you need.

**Comment by mgechev** [comment]
@inliquid I'm closing the issue. Feel free to comment/open a new issue in case I misunderstand.

**Comment by jan-xyz** [comment]
That would be my favorite solution 🤗 I would also offer to provide the PR for it, if you are ok with adding it

**Comment by jan-xyz** [comment]
I filed #589 , let me know what you think 🤗
