### ISSUE TITLE
vimrc blurb blows up if ale is still being installed

### ISSUE THREAD

**Issue by tommyjcarpenter** [mgechev/revive#242]
**Describe the bug**
If vim plugins like ale are not yet installed (eg open new vim for first time, and execute PluginInstall), the blurb in the instructions throws an error:

```
Error detected while processing /home/tommy/.vimrc:
line   68:
E117: Unknown function: ale#linter#Define
Press ENTER or type command to continue
```

 I think just the presence in the vimrc is causing the panic? One way to fix it seems to be to install ale, then add that to my vimrc; however im setting this all up in a dockerfile, so the vimrc already exists when plugininstall is called. Is there maybe a "try catch" or something that should be around that blurb?

I am using `Plugin 'w0rp/ale'`, before this.

**Desktop (please complete the following information):**
 - OS: Arch linux (atest
 - Version of Go: latest

**Comment by mgechev** [comment]
Hey @tommyjcarpenter, thanks for giving revive a try with vim! I'm not sure if this is an issue in revive itself? Maybe it's more of an ale related problem that it'll be a better fit for their repo?

Let me know if you think otherwise so we can discuss further.

**Comment by tommyjcarpenter** [comment]
hmm, I have other configurations for ale in my vimrc, but this is the only one that causes vim to barf. I agree the issue is likely related to ale, but I'm wondering whether there is another way to define this in the vimrc such that this doesn't happen. Basically, definitely not an issue with revive, but possibly an issue with the installation instructions for vim.

**Comment by mgechev** [comment]
@ndyakov shared this config. Nedyalko, do you have any comments?

**Comment by tommyjcarpenter** [comment]
normal usage probably wouldn't run into this btw; most people probably have ale installed, they see your great project, then they add the blurb to .vimrc, and it works. Or, they get the error, manually go past it to start vim anyway, go install ale, and then it works. 
However, we use development environments in Docker, so I install vim, vim's plugins, and copy in a vimrc all while building a container, and once vim throws the error, there is no way to continue past it. (my current workaround is to comment it out, then manually uncomment it once in the dev env).

**Comment by mgechev** [comment]
@tommyjcarpenter is there anything we can do on revive side here? Alternatively, I suggest to close the issue here.

**Comment by tommyjcarpenter** [comment]
I suppose I don't have an idea for that currently; will close unless I think of something.
