### ISSUE TITLE
Ability to specify `exclude` or `include` file / directories in config

### ISSUE THREAD

**Issue by jpopadak** [mgechev/revive#244]
**Is your feature request related to a problem? Please describe.**
I would love it if I could just point revive to a specific configuration file, and have it automatically pick up the `include` and `exclude` directories from that configuration file. I have some directories that are used for test helpers (multiple directories) with 50+ files and it is annoying to have to pass in the `--exclude` flag just to have it ignore them. 

**Describe the solution you'd like**
I would like a top level `exclude` and `include` variables that work just like the CLI `--exclude` and `--include` flags.

**Describe alternatives you've considered**
I currently use the CLI flags, but again, they get pretty long and having to use a bash variable to hold each one is annoying. On top of this, everyone on my team knows to look for the toml config file, and completely forget about the extra arguments on the CLI in some random CI/CD file.

**Additional context**

**Comment by mgechev** [comment]
Are you thinking of preserving the current semantics of `include`/`exclude` by getting all the files that match a pattern?

It's also interesting question what would be the result of combining a command line `include`/`exclude` with a config file. Do we override the config file or we get the union?

Override makes sense to me.

**Comment by jpopadak** [comment]
I would like to preserve the semantics. Maybe allow both `exclude` and `include` to be an array of strings, similar to multiple `-exclude` `-include` flags?

Override makes the most sense to me also.

**Comment by chavacava** [comment]
There is an `include` CLI flag? I think is not the case

**Comment by freedemster** [comment]
I think it's will be nice to have the ability to include/exclude files and directories for each rule. For example: disable some rules for several packages inside the project.

**Comment by mgechev** [comment]
Since the main purpose of the linter is introducing consistency across the entire project, to me it looks like applying certain rules to a subset of packages would be defeating the goal.

**Comment by jpopadak** [comment]
> Since the main purpose of the linter is introducing consistency across the entire project, to me it looks like applying certain rules to a subset of packages would be defeating the goal.

For our specific needs, we have a package that is just about wiring up dependencies. These few files we do not want to run the linter against. It would be even better if we could do on a per rule basis, because then we can enforce most rules but ignore a few for that given package.

**Comment by chavacava** [comment]
> For our specific needs [...] These few files [...]

You can disable revive at rule-level granularity by using [comment directives](https://github.com/mgechev/revive#comment-directives).

**Comment by peake100** [comment]
+1 on this. I have a CI/CD template that runs the linter for all my libs, so there isn't a great way to specify project-specific ignores right now.
