### ISSUE TITLE
[Question] some of the rules are not working by default

### ISSUE THREAD

**Issue by viveksinghggits** [mgechev/revive#265]
So of the rules that are mentioned there in the documentation are not working be default. I was expecting them to work. If we take example of the go file

https://gist.github.com/viveksinghggits/6ca0aface93ebc90503e13dc77f3255c

I was expecting revive to break at line 27, not handling returned error.
The code after line is not reachable, I dont get any warning for that. `unreachable-code` should do that.
lines 42, 44 and 46, 48 should be warned by rule `empty-lines`

I am doing something wrong, or these rules done work by default i will have to do some changes in config file.

**Comment by chavacava** [comment]
Hi @viveksinghggits, `revive` only applies those rules mentioned in the config file you pass in the command line through the flag `-config`. If there is no `-config` in the command line, `revive` will behave exactly as `golint` does.

**Comment by chavacava** [comment]
> The code after line is not reachable, I dont get any warning for that. unreachable-code should do that.

The line number is lacking in your sentence but I guess you are referring to line 39: I'm afraid that `revive`is still not  capable to detect unreachable code in that situation (i.e. an always true condition that leads to a `return` statement)
Contributions are welcome!

**Comment by viveksinghggits** [comment]
Hey @chavacava 
Thanks for the explanation, but by looking at this rule `unreachable-code` I thought that it should complain that the code after line 39 is not reachable. And I can see the rule `unreachable-code` in the documentation.

**Comment by chavacava** [comment]
@viveksinghggits, I've contributed the rule `unreachable-code`, the rule implementation is _sound_ (i.e. it does not return false positives) but it is _incomplete_ (it is not able to detect all the cases)

In **general**, detecting unreachable code is very hard (if not impossible) thus static analysis tools (like `revive`, or compilers) need to make a trade-of between completeness and soundness (and complexity!)
