### ISSUE TITLE
Support for regex/glob in -exclude

### ISSUE THREAD

**Issue by fgeckeler** [mgechev/revive#347]
Hi all,

**Is your feature request related to a problem? Please describe.**
I have a lot of generated files in my workspace which all end with '_generated.go' I would like to exclude them from revive/lint.

**Describe the solution you'd like**
Passing a regex or a [glob pattern](http://man7.org/linux/man-pages/man7/glob.7.html) to revive: `revive -exclude aWord` or `revive -exclude *_generated.go`

Thanks and best regards 
Florian

**Comment by chavacava** [comment]
Hi @fgeckeler, did you try to exclude them by using the `ignoreGeneratedHeader` config option (see [here](https://github.com/mgechev/revive#configuration))?

**Comment by fgeckeler** [comment]
Hi @chavacava,

we did not use generated headers. I added them now to our generator template.
I still think that excluding filename patterns could be really useful but for my use case the issue is solved.

Thanks for the response and best wishes
Florian

**Comment by chavacava** [comment]
Hi, now you can configure file exclusions at rule level.
Check #857 

(yes, soon we will need a linter for the `revive` configuration :smile: )
