### ISSUE TITLE
Application version support

### ISSUE THREAD

**Issue by JiriSko** [mgechev/revive#381]
Hi, thanks for this great tool.

Would be possible to add application version support in standard way? I mean to add `--version` CLI option which shows revive version.

**Comment by mgechev** [comment]
Maybe `revive -help` can show the current SHA. In general, I am hoping us to not have to stick to a particular version. Instead, revive is supposed to be an "evergreen" tool that anyone can use the last version of. That's one of the reasons I was originally against introducing semver to the project.

**Comment by JiriSko** [comment]
That would be helpful. I just want to see in my pipeline which version I'm using and this would be enough.

**Comment by nano-adhara** [comment]
+1 golint doesnt provide any information and i was hoping for this tool to provide such information on top of golint

**Comment by nvuillam** [comment]
@mgechev I also need --version for [Mega-Linter](https://nvuillam.github.io/mega-linter/) , please :)

**Comment by Clivern** [comment]
I can do this if my PR to add goreleaser got approved/released, since goreleaser already provide these info from git as ldflags. so it is just a matter of adding these vars to `main.go` and create a command to return them.

```
var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
	builtBy = "unknown"
)
```

**Comment by chavacava** [comment]
@Clivern #503 is merged ;)

**Comment by Clivern** [comment]
yeah, i will take care of this request then @chavacava
