### ISSUE TITLE
Include flag

### ISSUE THREAD

**Issue by rekby** [mgechev/revive#384]
**Is your feature request related to a problem? Please describe.**
I work with very large monorepo, which entire placed in gopath. Only small part of repo is go code. Smaller part - go code need for me. Now vscode take a lot of time when try scan full repo by default and I have hundreds exclude rules.

**Describe the solution you'd like**
I want "include" flag - for describe only packages, what I want to scan.

**Describe alternatives you've considered**
Now I use very many exclude rules.

**Comment by mgechev** [comment]
You can specify which packages you want to lint by setting the arguments of the binary:
```
revive github.com/mgechev/revive
```

This will be interpreted as "include github.com/mgechev/revive". That's what revive uses under the hood https://github.com/mgechev/dots.

**Comment by rekby** [comment]
It it my mistake of understand documentation of vscode - I read as about it linters for autocomplete. But it isn't.
