### ISSUE TITLE
ignoreGeneratedHeader inverted logic?

### ISSUE THREAD

**Issue by dominikschulz** [mgechev/revive#4]
Maybe I got the documentation wrong, but I think the logic evaluating the `ignoreGeneratedHeader` option is wrong.

When I set `ignoreGeneratedHeader = true` it will check my generated files, if I set it to `ignoreGeneratedHader = false` it will not check my generated files.

IMHO there should be no `!` in here: https://github.com/mgechev/revive/blob/master/lint/linter.go#L66

Is that correct?

**Comment by mgechev** [comment]
The property name looks ambiguous. The semantics is: "Ignore the header if the value is true," i.e., lint files with a generated header.

I'm open to suggestions to rename the config property. Until then, I'll update the docs.

**Comment by dominikschulz** [comment]
Ahhh, thanks a lot for the explanation and updating the docs. Now this makes a lot more sense :+1:
