### ISSUE TITLE
Feature Request: Customize initialisms or remove "ID" from the common list

### ISSUE THREAD

**Issue by cvbarros** [mgechev/revive#41]
**Is your feature request related to a problem? Please describe.**
In short, I'm looking for alternatives to `golint`, particularly because of this issue:
https://github.com/golang/lint/issues/89

**Describe the solution you'd like**
There are some options to implement this feature.
1. We could provide a "whilelist" of allowed initialisms, such as `Id`, in order to name variables such as `projectId` via configuration.  This is the most flexible option, but may lead to other initialisms than `Id` to be whitelisted, spreading inconsistency across Go projects.
2. Remove `ID` completely from the [initialism list](https://github.com/mgechev/revive/blob/5248ad8ed955d22005b47a1dbfdfa720b0e77ecb/lint/utils.go#L79). The comment on source code, similarly to Golint, states that "Freudian code is rare". However this rule creates warnings for several projects, such as [here](https://github.com/golang/protobuf/issues/156)
3. Refactor initialisms into its own rule other than `var-naming`, so it can be enabled/disabled as whole.

**Describe alternatives you've considered**
I've tried disabling the `var-naming` rule, but other effective idiomatic rules get disabled as well, so that's not an option.

**Additional context**
The lack of flexibility in Golint rules is something that this project can offer, along the speed.

I'd more than happy to give it a try at this myself, if applicable.

**Comment by mgechev** [comment]
We can make the rule configurable. I'd prefer to keep this check under `var-naming` so we can be as compatible with `golint` as possible.

If you have some spare time, it'll be great if you can give it a try! We can discuss the approach you're planning here so we can collect some more thoughts! // cc @chavacava

**Comment by chavacava** [comment]
As described by @cvbarros, the configuration with an optional (empty by default) white list of "relaxed" initialisms seems the most flexible approach. It may lead to inconsistencies across projects but not more than adding a new rule (option 3).

**Comment by mgechev** [comment]
@cvbarros I won't be able to work on it shortly. Assigned the issue to you so you can take care.

**Comment by mgechev** [comment]
I implemented this feature right [here](https://github.com/mgechev/revive/pull/61).

Let me know if you have other suggestions.
