### ISSUE TITLE
Warn on unused variables, functions and methods

### ISSUE THREAD

**Issue by iiinsomnia** [mgechev/revive#427]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chavacava** [comment]
@iiinsomnia detecting unused symbols requires to analyse packages as a whole. Currently `revive` applies rules file by file thus it can't determine if a symbol is not used.
Some time ago we discussed to extend `revive`'s analysis framework to allow developing _package wide_ rules (see #146

**Comment by iiinsomnia** [comment]
I see, thanks!

**Comment by chavacava** [comment]
@iiinsomnia I've just made public a [repository](https://github.com/chavacava/gusano) with a tool that detects unused symbols. The tool is something I use to experiment with new features for `revive` (package-wide analysis for example) therefore is far to be perfect and is not as ergonomic as `revive`.

**Comment by iiinsomnia** [comment]
OK！I will try it.
