### ISSUE TITLE
Rule specific include and exclude patterns

### ISSUE THREAD

**Issue by jwmach1** [mgechev/revive#446]
**Is your feature request related to a problem? Please describe.**
Similar to #244, and discussed in [those comments](https://github.com/mgechev/revive/issues/244#issuecomment-560509840)
A family of micro services that are contained in one repository. Some code is specific to individual services, other packages are shared/used for multiple services. To be specific, rules like `[rule.exported]` could be only enforced on code that is reused across the micro services. To run that rule, and other non-enforced rules, on the entire repository creates a problem of always seeing lint messages. This creates an overhead of needing to scan the listed lint messages to see if they fall into the not-enforced category.

**Describe the solution you'd like**
Introduce a new config parameter along side `arguments`. This new argument (`patterns`? -- I'm sure there's a better name} would be 1 or 2 slices of strings:
```
[rule.var-naming]
  arguments = [["ID"], ["VM"]]
  patterns =[["incl*regex1", "incl*regex2"], ["*exclude*regex"]]
```

The complexity I see is that `lint.File` struct only knows its name. Being limited to only use the filename in the include/exclude patterns would possibly cause an excessive list of items that would be a maintenance burden as new files are added to particular packages. It might also influence file naming patterns just to support the rule include/exclude regex. As my need is the same as that comment referenced above -- that certain packages have different lint-free expectations. I think this solution would need the `lint.File` struct to now its full path. Determining more information about the file (full path, Go package) might be an excessive performance cost -- at least something of which to be cognizant.

**Describe alternatives you've considered**
What if each package had its own TOML configuration file? Similar to `.gitignore`. Would child directory/package config files overwrite parent level configuration? Would it be necessary to support specifically disabling rules instead of relying on their absence. This solution seems excessive, heavy handed.

**Additional context**
The use of the go-doc annotations feels unwieldy to solve this problem. My perspective of those is for one-off situations where exceptions are warranted.

**Comment by mgechev** [comment]
What about having different configuration files for different parts of the project? This way you can enable a subset of them in particular directories.

I believe both approaches will have comparable ergonomics:
- More configuration & code to maintain
- Inconvenience of having an extra config file

**Comment by jwmach1** [comment]
Yes, I also considered the extra configuration file approach in the **Describe alternatives you've considered** section above. Do you envision the files are stand-alone or cumulative? I earlier only thought of the cumulative approach where config files in child directories build upon the rules found in higher directories. In this cumulative approach I saw rules needing to be added and removed.  However, given a series of configs, having each file be stand alone might be easier to maintain even though much duplication would exist.

**Comment by mgechev** [comment]
>However, given a series of configs, having each file be stand alone might be easier to maintain even though much duplication would exist.

They are stand-alone for the reasons you pointed. Trying to keep the feature set orthogonal to reduce the amount of flags and (potentially) conflicting options in the future.
