### ISSUE TITLE
consider add funlen as new rule

### ISSUE THREAD

**Issue by jasonkylelol** [mgechev/revive#484]
https://github.com/ultraware/funlen

**Comment by chavacava** [comment]
There are already some rules of that kind (eg line-length-limit) so why not.

**Comment by jasonkylelol** [comment]
it's different. line-length-limit warns when a line have characters over limit num. funlen warns when a function has too many lines.

**Comment by chavacava** [comment]
Hi @jasonkylelol, yes I understand that the goals of these rules are different, that's why I've said that I do not see any problem in adding that about function length.

**Comment by mgechev** [comment]
Sounds good to me.
