### ISSUE TITLE
Indirectly imported types have "invalid type"

### ISSUE THREAD

**Issue by jniedrauer** [mgechev/revive#490]
If a function returns a type declared in another package, you cannot determine the type in a linter rule. after running TypeCheck() and looking at the entry in TypesInfo.Defs, it has "invalid type".

A minimal reproduction would look like this:

a/a.go:
```
package a

import "errors"

func Err() error {
    return errors.New("")
}
```
example.go:
```
package example

import (
    "errors"

    "a"
)

var errInvalidType = a.Err()
var errValidType = errors.New("")
```
If you lint this file with a linter rule like the following:

```
func (w *lintRule) Visit(node ast.Node) ast.Visitor {
	n, ok := node.(*ast.GenDecl)
	if !ok {
		return w
	}

	if n.Tok != token.VAR {
		return w
	}

	spec := n.Specs[0].(*ast.ValueSpec)
	id := spec.Names[0]

	obj := w.file.Pkg.TypesInfo.Defs[id]
	fmt.Printf("%q has type %v\n", id.Name, obj)
}
```

You will get this output:

```
"errInvalidType" has type var main.errInvalidType invalid type
"errValidType" has type var main.errValidType error
```

This seems to be a problem with the importer from golang.org/x/tools/go/gcexportdata. I'm not able to reproduce this when I load the AST tree myself using golang.org/x/tools/go/packages instead.

**Comment by mgechev** [comment]
Revive currently does not perform cross-fire analysis. We've discussed it in the past and it's a trade-off between completeness and performance. What's your use case?

**Comment by jniedrauer** [comment]
I'm trying to write a linter rule that detects leaked connections; for example, leaked file descriptors or leaked HTTP request bodies. But type checking like this only works for files that call the core library directly. For files that call wrapper functions, types do not propagate and so it can't be done with revive.

**Comment by mgechev** [comment]
I remember @chavacava had fork of revive which allows cross-file type checking, but I can't seem to find it.

I'll be curious what's the performance penalty. I suppose it'll be significant because we'll no longer be able to lint individual files in separate go routines independently.

**Comment by jniedrauer** [comment]
Interesting. I guess I can see how that might have a performance impact, since the linter would need to recursively import all the imports of all of its imports. I don't think this would be slower than compiling though, and I would expect that the importer in golang.org/x/tools/go/gcexportdata is already doing that. If I'm reading it correctly, lint.Package.TypeCheck() uses a mutex to check types once for an entire package even when multiple files within the package are linted.

I'd be very interested in looking at the changes in that fork, if it exists.

**Comment by chavacava** [comment]
Hi, sorry for the late response.

You can check [gusano](https://github.com/chavacava/gusano) a sandbox project I've created to investigate package-wide analysis.
