### ISSUE TITLE
Requesting golangci-lint documentation in README.md

### ISSUE THREAD

**Issue by Zamiell** [mgechev/revive#518]
From #162, I am reading that `revive` is intended to be its own standalone-linter separate from golangci-lint.

With that said, I suspect that most new `revive` users will be using `revive` as a drop-in replacement for `golint` *using* golangci-lint, which is already the most popular Golang linter framework.

Currently, there is no mention of golangci-lint in the README.md file. After trying out the tool, I was very frustrated as soon as I attempted to configure one of the rules. Is documentation relating to golangci-lint something that can be added?

Specifically, the README.md describes how to generate a TOML config file, which is handy info. But in golangci-lint, you need to instead modify the .golangci.yml file and add something like the following, which is not obvious:

```yml
linters-settings:
  revive:
    rules:
     - name: exported
```

**Comment by chavacava** [comment]
Hi @Zamiell, thanks for the request. 

>Is documentation relating to golangci-lint something that can be added [to the README.md]?

Yes, of course. We can imagine a _Linter aggregators_ sub-section just after _Continuous integration_ describing how to configure `revive` under `golanci-lint`. If you can open a PR we will be glad to accept it.
