### ISSUE TITLE
Using golangci-lint is there a way to disable a single revive's rule?

### ISSUE THREAD

**Issue by frederikhors** [mgechev/revive#522]
I'm using golangci-lint 1.40.1.

Is there a way to disable a single revive's rule?

Such as:

```yaml
linters-settings:
  revive:
    rules:
      - name: exported
        deactivate: true
```

This doesn't work right now.

**Comment by chavacava** [comment]
Hi @frederikhors, 

I do not known how to configure `revive` from `golangci-lint` (there is an issue #518 waiting for a PR from someone that masters `golangci-lint`, if it is your case, we will be glad to accept a PR from you!)

By default, `revive` only enables rules that are named in the configuration, therefore if you want to disable a rule you just need to delete (or comment out) it from the configuration.

If you are trying to use the new [`enableAllRules` configuration option](https://github.com/mgechev/revive/issues/517) please take into account that `golintci-lint` [uses `revive` at version 1.0.6](https://github.com/golangci/golangci-lint/blob/5d84fa5ecd54c0cb3007fc3a3adc611ebe0f3bae/go.mod#L52) and that version does not include the new configuration option.

You can find more information in the [Configuration section](https://github.com/mgechev/revive#configuration) of the README.

Please let me know if you need more details on the subject.

**Comment by chavacava** [comment]
Hi @frederikhors, you can also check PR #523 that provides more information on how to configure `revive` in `golangci-lint`

**Comment by frederikhors** [comment]
@chavacava I will wait for a new golangci-lint version to try configuration in my project. Please do not close this.

**Comment by chavacava** [comment]
> @chavacava I will wait for a new golangci-lint version to try this configuration in my project. Please do not close this.

The master branch of `golangci-lint` already includes the `revive` version supporting `enableAllRules` configuration option.

https://github.com/golangci/golangci-lint/commit/b5d847f07f3059e2c3d8a52be50c8c1970f97f71

**Comment by frederikhors** [comment]
Yeah but it's still not released, right?

**Comment by chavacava** [comment]
I do not think so

**Comment by MorpheusXAUT** [comment]
Looks like this feature was released in version [1.0.7](https://github.com/mgechev/revive/releases/tag/v1.0.7) without a mention in the changelog - at least the [comparison](https://github.com/mgechev/revive/compare/v1.0.6...v1.0.7) shows the relevant PR 521 in the commits included.
1.0.7 was released on May 28th, now being supersede by [1.0.8](https://github.com/mgechev/revive/releases/tag/v1.0.8), released 3 days ago on June 25th.

As we're currently performing the migration from golint to revive on a big stack, we'd highly appreciate having the option to configure/disable some of revive's functionality to adopt it better to our needs.

**Comment by MorpheusXAUT** [comment]
Oh, sorry @chavacava, I must've lost track of which repository/issue I was looking at before posting this - I thought this was opened in the golangci-lint repo and we were waiting for a revive release 🙈 

Sorry for the confusion and for the hint, I'll make sure to check out the new config options tomorrow!

**Comment by chavacava** [comment]
@MorpheusXAUT you've spotted an actual problem in the release's changelog! Beyond that we are always glad to answer questions and help on using `revive`

I've checked `golangci-lint` releases and the version [v1.41.0](https://github.com/golangci/golangci-lint/releases/tag/v1.41.0) includes `revive 1.07`

**Comment by grosser** [comment]
FYI how I got it to work:
```
# .golangci.yml
linters-settings:
  revive:
    enable-all-rules: true
    rules:
    - name: dot-imports
      exclude: ["**/**/*_test.go"]
```
