### ISSUE TITLE
Disallow nested structs

### ISSUE THREAD

**Issue by rdeusser** [mgechev/revive#529]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Nested structs in projects are annoying and ugly. I'd like a rule that disallows them entirely.

**Describe alternatives you've considered**
I haven't really considered any alternatives. I'm not sure if there are any.

**Additional context**
For example:

```go
type Parameters struct {
	Options []struct {
		Value string `json:"value"`
	} `json:"options,omitempty"`
}
```

Is awful to look at. This is a 1000x better:

```go
type Option struct {
	Value string `json:"value"`
}

type Parameters struct {
	Options []Option `json:"options,omitempty"`
}
```

**Comment by chavacava** [comment]
Hi @rdeusser thanks for the rule proposal.

The rule is very opinionated. Considering nested structs "annoying and ugly" is very personal and a matter of style (I think that they are hard to read but that is me)
