### ISSUE TITLE
Extending defaults config

### ISSUE THREAD

**Issue by SamuelCabralCruz** [mgechev/revive#541]
**Is your feature request related to a problem? Please describe.**

I am wondering if there is any way to extend the default rules' configuration.
One such situation would be with import-blacklist which is an array formed of two crypto imports by default md5 and sha1, but to which I would like to add another entry. However, I don't want to "override" default values and still have update on best practices if default configurations have to evolve over time.

**Describe the solution you'd like**

I don't have a clear solution in mind other than have a keyword "&default" that would simply use the default provided value if any or raise an error otherwise.

Example:

```
[rule.import-blacklist]
  arguments = ['&default', 'some/new/package']
```
**Describe alternatives you've considered**

**Additional context**

**Comment by mgechev** [comment]
Let's keep the configuration as simple as possible for now unless this turns into a highly desired feature.
