### ISSUE TITLE
suppressing lint issues for lines

### ISSUE THREAD

**Issue by EmmetZC** [mgechev/revive#545]
**Is your feature request related to a problem? Please describe.**
Sometimes, I would like to ignore some lint errors/warnings instead of simply refactor it. Especially var naming problems since fixing it may cause compatibility issues.

**Describe the solution you'd like**
use `// nolint` comment or something similar to ignore one line or the line after. For example:
```golang
type User struct {
	//nolint:revive User's ID
	UserId string 
	// User's Name
	UserName string
	// User's Blog URL
	UserBlogUrl string //nolint:revive
}
```
I wish `//nolint:revive` would suppress the var-naming warning/error of `UserId` and `UserBlogUrl` while linter keeps fully functional for other lines.

**Describe alternatives you've considered**

**Additional context**

**Comment by chavacava** [comment]
Hi @EmmetZC  thanks for filling the issue. Could you please check if [comment directives](https://github.com/mgechev/revive#comment-directives) do what you are requesting?

**Comment by EmmetZC** [comment]
> Hi @EmmetZC thanks for filling the issue. Could you please check if [comment directives](https://github.com/mgechev/revive#comment-directives) do what you are requesting?

Wow, thanks a lot. That's exactly what I've been looking for. Guess I've just missed that part. XD
