### ISSUE TITLE
Apply default settings for some checks in golangci-lint

### ISSUE THREAD

**Issue by jawnsy** [mgechev/revive#579]
**Is your feature request related to a problem? Please describe.**

Some checks in golangci-lint, such as `argument-limit` and `cognitive-complexity` cause a panic if no argument is supplied. It would be nice to have a default value in this case, rather than a panic like:

```
panic: not enough arguments for argument-limit rule, expected 1, got 0. Please check the rule's documentation

goroutine 6485 [running]:
github.com/mgechev/revive/rule.checkNumberOfArguments(...)
        github.com/mgechev/revive@v1.1.1/rule/utils.go:197
github.com/mgechev/revive/rule.(*ArgumentsLimitRule).Apply(0xe0e740, 0xc005092570, {0x1946808, 0x0, 0x0})
        github.com/mgechev/revive@v1.1.1/rule/argument-limit.go:15 +0x1b9
github.com/mgechev/revive/lint.(*File).lint(0x938ac0, {0xc000680400, 0x38, 0x40}, {0x1, 0x3fe999999999999a, {0xc004400c40, 0x7}, 0x0, 0xc005092570, ...}, ...)
        github.com/mgechev/revive@v1.1.1/lint/file.go:108 +0x19b
github.com/mgechev/revive/lint.(*Package).lint.func1(0x0)
        github.com/mgechev/revive@v1.1.1/lint/package.go:173 +0x85
created by github.com/mgechev/revive/lint.(*Package).lint
        github.com/mgechev/revive@v1.1.1/lint/package.go:172 +0xb1
```

**Describe the solution you'd like**

Apply a default argument if none is supplied.

**Describe alternatives you've considered**

I've added some settings to the .golangci.yml based on the documentation, but it would be nice to have sensible defaults applied in the event that someone enables the linter before reading the documentation.

**Additional context**

I'm using the current release version of golangci-lint, downloaded from Releases:

```
$ golangci-lint --version
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z
```

**Comment by chavacava** [comment]
Hi @jawnsy, thanks for filling the issue.
This is a subject we have already discussed. Setting defaults for these rules is something we decided not to do.
The configuration is already very flexible (global/per rule settings, all/individual rule activation, ...) and allows you to deeply tweak revive's behavior. 
If someone is able to read the documentation to known how to activate all rules it is very likely that she/he will also read the next lines of the doc:
>When enabling all rules you still need/can provide specific configurations for rules.

**Comment by jawnsy** [comment]
Thanks so much for your reply and sorry for filing a duplicate (I only checked open issues and didn't do a search). I'll close this issue out. As one of the maintainers, it's ultimately your call and I respect your decision.

My humble opinion as a user of this software is that it's better to have reasonable defaults where possible, and minimize the amount that people have to read in order to use the tool to begin with. If someone enables `argument-limit` without configuring a threshold, I think it's better to get unwanted warnings (e.g. "arguments exceed 5"), which can then be modified as needed, than to get a panic.

I imagine that all of these arguments were brought up before and weren't sufficiently convincing to motivate a change, so I'm certainly not going to be stubborn about it :)

Thanks for maintaining this great software!

**Comment by chavacava** [comment]
Side note: it is possible that `golangci-lint` maintainers will accept to set default values for `revive` rules. The place to set these default values seems to be https://github.com/golangci/golangci-lint/blob/c6c55d2502b052e2e5925389ee40b6bde887e3db/pkg/golinters/revive.go#L152
