### ISSUE TITLE
Exclude files for specific rules

### ISSUE THREAD

**Issue by rkuska** [mgechev/revive#58]
I would like to have an option to exclude certain files for specific rules.

Example - revive.toml config file:

```
[rule.cyclomatic]
  arguments = [10]
  exclude= "path/to/the/file.go"
```

Now when revive runs it will not check "path/to/the/file.go" for cyclomatic rule.

**Comment by mgechev** [comment]
@rkuska currently you can achieve this with comment annotations. In `file.go` add a comment:

```go
//revive:disable:cyclomatic
```
