### ISSUE TITLE
1.1.3 release checksum has changed

### ISSUE THREAD

**Issue by iMichka** [mgechev/revive#634]
**Describe the bug**

Hi. I am a maintainer of the Homebrew package manager.
We noticed that the checksum of the 1.1.3 release has changed from 8aab7c604229a40f443a5fb3b1112b7ebb0b8e31 to baa70eb87ce60e5905df49d63815a9f712c8058f

This is a major security issue as upstream release checksums are not supposed to change. Did you retag the release (which is something that should never be done, see https://git-scm.com/docs/git-tag#_discussion). Or did someone gain access to your repo?

See https://github.com/Homebrew/homebrew-core/pull/95106 for the issue on our side.

**To Reproduce**

Compare the checksum of the old and new release.

**Expected behavior**

No checksum change

**Logs**

NA

**Desktop (please complete the following information):**

All OSes

**Additional context**

NA

**Comment by mgechev** [comment]
Sorry about that. Feel free to use v1.1.4 that I just published and includes the latest fixes by @chavacava.
