### ISSUE TITLE
Allow configuration to be passed in to library mode

### ISSUE THREAD

**Issue by heynemann** [mgechev/revive#654]
I was checking how golangci-lint [uses revive](https://github.com/golangci/golangci-lint/blob/30c6166b08117b0b19ec44c26c7e97c1506656ba/pkg/golinters/revive.go) and they seem to have copied a substantial part of the codebase.

Now that it is possible to run revive as a library I was thinking of making a PR to golangci-lint to improve revive's usage there. The only thing missing is passing in configuration and being able to call revive without the CLI arguments (why they copied I believe).

Do you think it is a good step forward? Decoupling the CLI part with the linting part of revive? I can get a draft PR...

**Comment by chavacava** [comment]
After merging your last PR I immediatly thinked on golang-ci and how we could facilitate the integration of revive.

**Comment by heynemann** [comment]
Will get a draft PR as soon as possible for us to work on this...

**Comment by chavacava** [comment]
Closed by #655
