### ISSUE TITLE
Add SemVer releases

### ISSUE THREAD

**Issue by z0mbie42** [mgechev/revive#66]
**Is your feature request related to a problem? Please describe.**
The idiomatic way to create software is to publish releases when required (fix, new feature, api break...).
There is currently no versioning for `revive`.

**Describe the solution you'd like**

I would like to suggest https://github.com/astrocorp42/rocket to automate GitHub releases.
Thus We can automate releasing and binaries publishing.
Furthermore it would enable automated **Docker** publishing which is great for users of services like drone.io. 

It would requires a `Makefile` (for example: https://github.com/astrocorp42/rocket/blob/master/Makefile), to build `revive`.

**Describe alternatives you've considered**
https://github.com/goreleaser/goreleaser but it mix too many things (build + publishing).

**Comment by mgechev** [comment]
Let's collect some more feedback here before we proceed.

**Comment by z0mbie42** [comment]
The case I encountered today was the following:
I use revive for one of my projects during the tests in the CI pipeline (in a docker container). The pipeline failed because revive was not at the good version and the `unix` formatter was not available because Docker cacher this `go get -u github.com/mgechev/revive` step.

`go get` unfortunately cannot enable to download a specific version of a go program, this is why I think providing binaries for each version is a *very good idea*. (thus we can pin our revive version in our CI pipelines). And there is absolutely no cost to do this.

@chavacava +1 for the changelog idea, but it's really a panacea and very error prone to do it manually and can be easily automated by extracting information from commit messages.
Do you have an idea about what tool to use to automate the changelog generation ?

**Comment by mgechev** [comment]
Let's tag the individual versions without publishing binaries for now. If we see this feature request again, we can reconsider.

**Comment by mgechev** [comment]
1. In the Angular team we have weekly patch releases monthly, major releases, and bi-weekly annual releases. We can introduce a similar schedule. Every new feature will be available in the master branch, so people who want to live on the edge can (feel free to propose a better release workflow)
2. I think we can keep it simple for now without LTS

**Comment by chavacava** [comment]
1. Do you refer to [this schedule](https://angular.io/guide/releases#release-frequency)? LGTM
2. I agree.

Do we start with 1.0.0? When?

**Comment by mgechev** [comment]
We can start tagging releases when https://github.com/mgechev/revive/pull/106 lands. I hope we're able to put some more thoughts into it by then.

**Comment by albertorestifo** [comment]
Any update on this? Having tagged releases would be really helpful

**Comment by mgechev** [comment]
I'd prefer if we keep the release cycle the way it is right now. It's trivial to incorporate security updates downstream and we haven't introduced any breaking changes which require lock to a particular version.

I'd revisit this while the project evolves. Let's close for now.

**Comment by jpopadak** [comment]
Any chance of doing this now that Go 1.13 has been released? I believe the official Go Sum server does not hold the sums of all versions for a given branch (including master) and will return 410 GONE if it cannot find an old version sum in its database. It does, however, hold semver tags to a specific version.

**Comment by mgechev** [comment]
Let me reopen.

**Comment by PaperMountainStudio** [comment]
The lack of releases is also stopping packaging for distributions.

**Comment by chavacava** [comment]
@mgechev what do you think about tagging and releasing v1.0.0 ?

**Comment by mgechev** [comment]
Sure, let me create the v1.0.0 tag and push it.

**Comment by mgechev** [comment]
https://github.com/mgechev/revive/releases/tag/v1.0.0

**Comment by PaperMountainStudio** [comment]
Thanks

**Comment by PaperMountainStudio** [comment]
https://github.com/void-linux/void-packages/pull/18004 😉
