### ISSUE TITLE
New Rule for warning when fields are not set when initialising a struct

### ISSUE THREAD

**Issue by johan-lejdung** [mgechev/revive#682]
**Is your feature request related to a problem? Please describe.**
Given the nature of Go there is a lot of translating one struct to another (eg, Create Payload to an Update Payload or simliar). I'm always frustrated when I'm adding new fields, and have to manually remember each mapping function I have. Often times a mapper is forgotten without any visible warnings, and only discovered once a bug is encountered. 

**Describe the solution you'd like**
I would love to have a rule that warns if there are any unset fields in a struct initialisation. The rule would only kick in place when one or more fields are defined. 

No Warning:
```
type MyStruct struct {
   FirstName string
   LastName string
}

var ex MyStruct = MyStruct{}
```

Warning:
```
type MyStruct struct {
   FirstName string
   LastName string
}

var ex MyStruct = MyStruct{ FirstName: "Hello" }
```

**Describe alternatives you've considered**
I've looked around for solutions, but writing a custom linter seems like the only option here without changing the code structures to rely on generated code or similar solutions.

**Comment by chavacava** [comment]
Hi @johan-lejdung thanks for filling the issue.
As you, sometimes I'm not quite comfortable with GO's structure initialization, and as you, I've searched for some idioms to avoid problems like the one you mention.

Here are some remarks about this subject:
1. GO's philosophy is to [Make zero value useful](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=6m25s)
2. As Rob Pike mentions in the above video sequence: in some cases a constructor is the right solution. (at my previous work I've developed a rule to spot structs with "too much fields" and recommend providing a constructor for them.)
3. A rule like the one you are asking for, to be useful, will require a global (module-wide) analysis. Typically, structs are declared in one package and used by other packages. `revive` is not able to perform that kind of analysis, it does file-wide analysis only.
4. To get a (compiler!) "warning" when you do not initialize all the fields of a struct you can use the hack I explain [here](https://chavacava.github.io/others/2022-03-01-go_pills.html#pill-1-forcing-to-use-field-names-when-instantiating-structs)

**Comment by johan-lejdung** [comment]
Hi @chavacava, thanks for the detailed response!

You raise good points, although there are some workaround it's a bit clunky. For example there is no way to enforce use of constructors, so even if you use one it's not immediately clear that the struct should only be initialised through constructors.

Additionally depending on the use-case it can be very hard to make zero-value useful. But I'm getting around it, a linting rule like this would be very helpful though. 

As I'm typing this, I thought of a another rule that could help solve the same issue. Would the analysis be smaller if the revive could warn when using a struct directly when that struct has constructors available in the same package?

eg. using `Test{}` in the below code could give off a warning.
```
type Test struct {
   Hi string
}

func NewTest(s string) Test {
 ...
}
```

**Comment by mgechev** [comment]
Let's close this feature request for now.
