### ISSUE TITLE
More initialisms

### ISSUE THREAD

**Issue by scop** [mgechev/revive#685]
**Is your feature request related to a problem? Please describe.**

I can think of a bunch of common acronyms that would be good to have built in as initialisms in revive.

**Describe the solution you'd like**

BGP, DB (as in database), MAC (as in address), SCSI, SDN, VRF added.

MAC could be a bit controversial, but I don't see the other ones causing false positives. Not all of them are _that_ common though, but I'd say at least DB is.

**Describe alternatives you've considered**

Local config.

**Additional context**

None.

**Comment by chavacava** [comment]
Hi @scop 
The rule `var-naming` already accepts as parameter a list of initialisms to check and a list of initialisms to ignore.
You can check the [rule's documentation](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming)
For technical details check the [related commit](https://github.com/mgechev/revive/commit/90f51530cc4b7bc0aafc9f8a28c874f1a43143fa)

**Comment by scop** [comment]
I know, that's what I referred to by "local config" in the initial commit. The point here was to add some common built in ones that people would not have to do that.
