### ISSUE TITLE
Package comment is not confidence

### ISSUE THREAD

**Issue by okhowang** [mgechev/revive#693]
**Is your feature request related to a problem? Please describe.**
Currently, a file without doc is reported by rule `package-comments` with confidence 0.2 .
but it is not check is there other files in package have doc.
I want make this rule more confident

**Describe the solution you'd like**
check package comment in package level

**Describe alternatives you've considered**

**Additional context**
I have build a [branch](https://github.com/okhowang/revive/tree/feat/package-comment) for this issue

**Comment by chavacava** [comment]
Hi @okhowang thanks for taking the time of creating the issue and developing a fix. Could you please create the pull request to integrate your code?

**Comment by okhowang** [comment]
There is no way to let the linter know which type of target (package/directory/file) it is checking as far as I know.
We shouldn't check package comments when lint on file level.
