### ISSUE TITLE
error-strings function list should be user configurable

### ISSUE THREAD

**Issue by oschwald** [mgechev/revive#697]
**Is your feature request related to a problem? Please describe.**

Our code-base has error strings that are not being checked by `error-strings`.

**Describe the solution you'd like**

Currently, `error-strings` uses a [hardcoded list](https://github.com/mgechev/revive/blob/04728cf0de86ab99fb3327a1ea48f7d51a411352/rule/error-strings.go#L20-L32) of functions that it checks. We use an internal package for generating errors that is not covered by the list. It would be nice there was a configuration option to add additional functions.

**Describe alternatives you've considered**

Potentially, we could write our own Ruleguard rule or use another linting package. We could also rename our internal package to `errors`, which I think would end up working given the current error functions we have and my understanding of how `error-strings` works.

**Comment by git-hulk** [comment]
@chavacava I would like to resolve this issue if no one took it.
