### ISSUE TITLE
can revive running on the goland

### ISSUE THREAD

**Issue by godcong** [mgechev/revive#7]
i added an revive [file watchers] in goland
and it is not running...

**Comment by mgechev** [comment]
I'm using vim & VSCode, not sure how we can add revive to goland and I have no way to test it. It'll be great if anyone with goland experience shares their thoughts!

**Comment by godcong** [comment]
i edit the file watcher like this.
it running!!!
![image](https://user-images.githubusercontent.com/2727298/40908617-dd48828c-6819-11e8-9265-7a0f55ba5178.png)
