### ISSUE TITLE
gcexportdata.NewImporter: huge impact on performance

### ISSUE THREAD

**Issue by ldez** [mgechev/revive#713]
**Describe the bug**

`gcexportdata.Find` has been rewritten:

- https://go-review.googlesource.com/c/tools/+/310515
- https://github.com/golang/tools/commit/2a900561e78a69afe5828ff8388aeb0dfc6220dc

`gcexportdata.NewImporter` uses `gcexportdata.Find`.

And `revive` uses `gcexportdata.NewImporter`:
https://github.com/mgechev/revive/blob/60e1ae4a014ff158513922aff1597ec974945546/lint/package.go#L30

**To Reproduce**
1. update `golang.org/x/tools` to `v0.1.12-0.20220628192153-7743d1d949f1`
2. build a binary
3. clone https://github.com/kubernetes-sigs/cluster-api
4. run the binary 

**Expected behavior**
Run fast

**Logs**

-

**Desktop (please complete the following information):**
 - OS: Linux
 - Version of Go: all versions

**Additional context**

`gcexportdata.NewImporter` and `gcexportdata.Find` are now deprecated.

https://github.com/golangci/golangci-lint/issues/2997#issuecomment-1190449973

**Comment by Trim21** [comment]
it looks like this function is only for go files' type checking.

**Comment by ldez** [comment]
@Trim21 The replacement is defined inside the deprecation notice: https://github.com/golang/tools/blob/79f3242e4b2ee6f1bd987fdd0538e16451f7523e/go/gcexportdata/importer.go#L26

**Comment by chavacava** [comment]
Hi @ldez, thanks for proposing this improvement. I'll work on it in the next days.

**Comment by chavacava** [comment]
Update: I have a working version where the problematic lib was replaced with `go/packages` (huge modif)
PR: #716 

TODO:
1. check if perf is better wrt the `master` branch
2. fix test data (`go/packages` requires go files to be compilable... testdata are syntactically OK but it do not necessarily compile :( )
3. only type check if a type-dependent rule is activated (at the moment type information is always calculated) This has an impact on performance.
4. clean-up the code

**Comment by chavacava** [comment]
Using `packages` in place of `gcexportdata` beaks some (important) things and I did not find simple solutions:
- Now the code to be analyzed needs to compile. Before a syntactically correct code was enough. (will need to update all the `testdata`)
- Now `revive` needs to be aware if the analyzed code is developed as a `mod`ule or not. Before `revive` just run on any code base

**Comment by ldez** [comment]
`golang.org/x/tools` has created a release v0.12.0 with the new implementation of `gcexportdata.Find`.

I don't know how I can help you.

related to #720

**Comment by mgechev** [comment]
I'll connect with the Go team and see if there's anything we can do.

**Comment by mgechev** [comment]
Looks like lots of folks are out of office. Seems like `NewImporter` is deprecated. I put together a quick fix. Wondering if it resolves the performance issue? https://github.com/mgechev/revive/pull/723

**Comment by ldez** [comment]
you can clone https://github.com/kubernetes-sigs/cluster-api to test your PR

**Comment by ldez** [comment]
I tested your PR, it seems to work

**Comment by Trim21** [comment]
tested, looks good

**Comment by ldez** [comment]
I did tests inside golangci-lint and it seems to works as expected.

**Comment by mgechev** [comment]
Thanks for giving it a try! I'l let @chavacava review and merge.

**Comment by mgechev** [comment]
Released in v1.2.2.

**Comment by mgechev** [comment]
The release failed. @doniacld, @Clivern if you have a moment would you check `.goreleaser`? Looks like it complains about failing build for windows arm64.

**Comment by mgechev** [comment]
Moved windows_arm64 to the ignore list of `.goreleaser.yml` for now.

**Comment by ldez** [comment]
Maybe you can create a different issue to track this problem?

**Comment by Clivern** [comment]
it seems `goreleaser` dropped windows arm64 support for go < 1.17 for some reasons.

```zsh
$ goreleaser check

   • loading config file       file=.goreleaser.yml
   • checking config:
   • DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
   • config is valid
```

Anyways i opened a PR to use 1.19 for release since i see we did the upgrade! also removed 1.16 build that keeps failing. https://github.com/mgechev/revive/pull/727

**Comment by mgechev** [comment]
Good catch, @Clivern! Thank you for the fix.
