### ISSUE TITLE
prefer XDG_CONFIG_HOME for getting the revive.toml config file

### ISSUE THREAD

**Issue by notjedi** [mgechev/revive#724]
**Is your feature request related to a problem? Please describe.**
A lot of linux programs prefer `XDG_CONFIG_HOME` for default configuration. So a lot of linux users might prefer the default `XDG_CONFIG_HOME` instead of `HOME`.

**Describe the solution you'd like**
Check for the `revive.toml` file in `XDG_CONFIG_HOME` first and then check for it in `HOME`(for backward compatibility)

**Comment by chavacava** [comment]
Closed by #912
