### ISSUE TITLE
Rules documentation

### ISSUE THREAD

**Issue by chavacava** [mgechev/revive#74]
**Is your feature request related to a problem? Please describe.**
Some warning/error messages generated by rules are not enough to clearly understand what is wrong  in the code or, more important, _why_.

Linters are a good source of knowledge for beginners, we can learn from reported warnings/errors.

 For example, a warning `use i++ instead of i += 1` does not provide any clue about why we should prefer `i++` 

**Describe the solution you'd like**
Add a document that describes the spirit of rules. The document may also describe rule configuration details.

**Describe alternatives you've considered**

Java's [FindBugs checks documentation](http://findbugs.sourceforge.net/bugDescriptions.html) is a good example.

**Comment by mgechev** [comment]
The proposal sounds good. With [codelyzer](https://github.com/mgechev/codelyzer), for each rule, we add a link to the Angular style guide.

What about creating a GitHub page which contains a more detailed description of the individual rules. In the rule failure message, we can add the link with an anchor to the corresponding description.

**Comment by chavacava** [comment]
> What about creating a GitHub page which contains a more detailed description of the individual rules. In the rule failure message, we can add the link with an anchor to the corresponding description.

:+1: 
I can start working in a first version of such a page. Do you have a suggestion for the name of the page?

**Comment by mgechev** [comment]
We currently have https://revive.run. We can reuse this domain if you don't have anything else in mind?

I did a short research on what we can use for the page. Here are few suggestions:

- [Docusaurus](https://docusaurus.io/)
- [docz](https://www.docz.site/)
- Next.js
- Gatsby
- Nuxt.js

An advantage of Next.js, Nuxt.js, and Gatsby is that if the website grows we can use predictive prefetching with Guess.js.

**Comment by mgechev** [comment]
@chavacava let me know if you have a more robust idea.

**Comment by chavacava** [comment]
For the moment I'm writing rules descriptions in a .md document. The doc can be used directly as you described in your previous comment (linking to thigs like https://revive.run/r/#time-naming) or serve (at leas its content) as the basis for other more elaborated solution (like serving it through technos like Next.js)

I have the description of half of the rules, I'll try to finish the doc for the next week.

**Comment by mgechev** [comment]
I worked on the docs [website](https://guess-js.github.io/website/) for Guess.js. I'm planning to approach the same way with revive. We can have rules page with titles so that https://revive.run/r/#rule-id will be a link to the rule with the name `rule-id`.

I can also add a brief guide to creating a rule & a formatter.

Let me know what you think.

**Comment by chavacava** [comment]
Hi @mgechev, it sounds good. The guides for rules & formatters are very important also. Let me know if I can help.

**Comment by mgechev** [comment]
@chavacava just finished the website. You can find it [here](https://revive.run/).

**Comment by chavacava** [comment]
Nice work!
(The [DOC](https://godoc.org/github.com/mgechev/revive) shows that we need to add some package comments :) )
