### ISSUE TITLE
Please release a new patch version.

### ISSUE THREAD

**Issue by jan-dubsky** [mgechev/revive#747]
We'd love to upgrade to the latest version of `go-revive` because of Go 1.19 support. Unfortunately our codebase uses many single-line functions, so the bug in #739 blocks us from upgrading. Would it be possible to release a new patch version of `go-revive` so that we can upgrade? Thank you!

**Comment by rawen17** [comment]
We have the same issue and ask to please release a new version. Thank you!

**Comment by psmarcin** [comment]
I have similar situation. Please bump version.

**Comment by mgechev** [comment]
Just pushed https://github.com/mgechev/revive/releases/tag/v1.2.4 and waiting for the GitHub action to release.
