### ISSUE TITLE
[rule.add-constant] add ''ignoreFuncs' to exclude constants in functions

### ISSUE THREAD

**Issue by rawen17** [mgechev/revive#751]
**Is your feature request related to a problem? Please describe.**
I want to add 'ignoreFuncs' in configuration
to have a possibility to exclude constants in functions

```
[rule.add-constant]
  arguments = [{'ignoreFuncs="println,os.Chmod"}]
```

**Describe the solution you'd like**
I want to create PR with changes, which add this feature

**Comment by chavacava** [comment]
Hi @rawen17, thanks for the proposal!
Could you please explain what is the problem you are addressing?
Your proposal is to skip rule application on specific function bodies or in specific function calls?
For example, imagine `ignoreFuncs="println"` when analyzing a source file with a function call as the following
```go
println("The result of calling myFunc is: ", myFunc(1))
```

Do you expect the rule to take into account (count in fact) the literal `1`?

**Comment by rawen17** [comment]
Hi, @chavacava ! 
I want to add function names in configuration to exclude checking magic numbers in function calls.
(skip rule application to specific function calls)
For example 
`"ignoreFuncs": "os.*,.Println,ignoredFunc",`
```
        println(0666)           // MATCH /avoid magic numbers like '0666', create a named constant for it/
	os.Chmod("test", 0666)  // ignore
	os.FindProcess(102100)  // ignore
	fmt.Println("test", 12) // ignore
	fmt.Printf("%d", 100)   // MATCH /avoid magic numbers like '100', create a named constant for it/
	ignoredFunc(1000)       // ignore
	println("The result of calling myFunc is: ", ignoredFunc(100)) // ignore
	println("The result of calling myFunc is: ", notIgnoredFunc(100)) // MATCH /avoid magic numbers like '100', create a named constant for 
```
In your example rule will be excluded if 'myFunc' is in 'ignoreFuncs'

**Comment by chavacava** [comment]
@rawen17 Could you please describe the use case you are addressing?

**Comment by chavacava** [comment]
I see, thanks @xobotyi.
I'll not discuss the convenience of writing
```go
os.Chmod("test", allowRead | allowWrite)
```
vs 
```go
os.Chmod("test", 0666)
```
If for example, `os.Chmod` is in the ignore list, how the rule will apply to a call like:
```go
os.Chmod(generateFilename("test"), 0666)
```
The instance of `"test"` literal is ignored in the counting of repetitions of the literal?
