### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by wojtekxtx** [mgechev/revive#768]
Exacty this.

Lead developer of `wojtekxtx/crowdsec` here. Trying to implement `revive` as per your horrible docs. Awful, not helpful at all.

Instead of shipping meaningless docs, maybe its assable to screw it all?

**Comment by chavacava** [comment]
Closing it until some intelligible sentence emerges.

**Comment by mgechev** [comment]
Closing and locking due to trolling :)
