### ISSUE TITLE
Remove deprecated io/ioutil package from the source code

### ISSUE THREAD

**Issue by alexandear** [mgechev/revive#806]
**Is your feature request related to a problem? Please describe.**

Package [io/ioutil](https://pkg.go.dev/io/ioutil) deprecated since Go 1.16:
```
Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os,
and those implementations should be preferred in new code.
See the specific function documentation for details.
```

**Describe the solution you'd like**

- Replace `ioutil.Discard` with `io.Discard`.
- Replace `ioutil.ReadFile, ioutil.WriteFile, ioutil.ReadDir` with `os.ReadFile, os.WriteFile, os.ReadDir`.

**Comment by mgechev** [comment]
Opened #825 and will merge once @chavacava approves.
