### ISSUE TITLE
dots.resolveImportedPackage excludes pkg.XTestGoFiles

### ISSUE THREAD

**Issue by srosenberg** [mgechev/revive#812]
**Describe the bug**

While running `revive` on [CockroachDB](https://github.com/cockroachdb/cockroach), I noticed that only a subset of the source files were being passed into a linter. After tracking down the root cause, the bug is in the `dots` library which excludes test files _outside_ of the package (e.g., `package foo_test`).

**To Reproduce**

I've cloned `https://github.com/mgechev/dots` and added `main` to enumerate all source files,

```
cat cmd/main.go
package main

import (
	"fmt"
	"github.com/dots"
	"os"
)

func main() {
	result, err := dots.Resolve([]string{os.Args[1]}, []string{})

	if err != nil {
		panic(err)
	}
	for _, f := range result {
		fmt.Println("listing", f)
	}
}
```

Running this against [CockroachDB](https://github.com/cockroachdb/cockroach),

```
./dots $GOPATH/src/github.com/cockroachdb/cockroach/pkg/... |wc -l
    5957
```

After applying the patch to include the missing test files,

```
@@ -116,6 +117,7 @@ func resolveImportedPackage(pkg *build.Package, err error) ([]string, error) {
        files = append(files, pkg.GoFiles...)
        files = append(files, pkg.CgoFiles...)
        files = append(files, pkg.TestGoFiles...)
+       //files = append(files, pkg.XTestGoFiles...)
        if pkg.Dir != "." {
                for i, f := range files {
                        files[i] = filepath.Join(pkg.Dir, f)
```

Running with the patch,

```
./dots $GOPATH/src/github.com/cockroachdb/cockroach/pkg/... |wc -l
    6717
```

**Expected behavior**

I expected _all_ source files to be enumerated by default. This corresponds to all `GoFiles`, `CgoFiles`, `TestGoFiles`, and `XTestGoFiles` as produced by `go list` against `$GOPATH/src/github.com/cockroachdb/cockroach`, 

```
go list -f '{{ .Dir }} {{ .GoFiles }} {{ .CgoFiles }} {{ .TestGoFiles }} {{ .XTestGoFiles }}' ./...  |tr -d '[' |tr -d ']' |awk '{for (i=2; i<=NF; i++) { printf("%s/%s\n", $1, $i)}}'|wc -l
    6717
```

**Comment by chavacava** [comment]
Closing because this is a `dots` library bug (not `revive`'ś  one)
