### ISSUE TITLE
Idea: minimum block size for indent-error-flow/early-return

### ISSUE THREAD

**Issue by mdelah** [mgechev/revive#816]
**Is your feature request related to a problem? Please describe.**
I find the `indent-error-flow` and `early-return` rules quite useful for finding large chunks of code that can lose an indentation level, but I'd prefer they didn't fire if the block in question was small (e.g. 1-2 lines), _especially_ if it requires moving an `if`-initializer to a separate line. I'm talking in particular about constructions of the form:

```
if foo, ok := Foo(); ok {
  foo.Bar()
} else {
  panic("!")
}
```
and
```
if foo, ok := Foo(); !ok {
  panic("!")
} else {
  foo.Bar()
}
```

The rules suggest reducing the indentation of the line `foo.Bar()` by one level by doing:

```
foo, ok := Foo()
if !ok {
  panic("!")
}
foo.Bar()
```

In terms of readability it does not seem like a clear win to me. The overall line count is unchanged (at 5), we increase the scope of the `foo` and `ok` variables in order to do it, and we only end up deleting a single tab character. Constructions like these are far more common (at least in my code base) than those where the `indent-error-flow` and `early-return` suggestions are helpful to me.

**Describe the solution you'd like**
I was wondering if the maintainers would consider configuration of some form to suppress such cases, to improve the signal-to-noise ratio. For example, a minimum count of lines that will be unintended to justify splitting an `if`-initializer onto a separate line. I'm happy to the supply code if desired.

**Describe alternatives you've considered**
- Could just bake in a reasonable minimum block size (say 2 or 3), and not have any extra configuration.
- Could have an option to simply never make such suggestions if there's an `if`-initializer.
- Could have separate block size thresholds for the case when there is an `if`-initializer and when there isn't.

**Additional context**
N/A

**Comment by chavacava** [comment]
Hi @mdelah, thanks for the proposal.
I think we could: 
1. add an option to do not suggest the refactoring when there is in if-initializer, and 
2. (in absence of this option) let the rule calculate itself if the potential refactoring provides a decrease in lines count and suggest the modification only if it is the case.

What do you think?

**Comment by mdelah** [comment]
Hi @chavacava, thanks for taking a look.

The trouble with (2) is that, provided there is an if-initializer, this type of refactoring will _never_ decrease the line count (we gain one for putting the initializer on a separate line, and lose one for the `} else {`, so we always break even). So the more relevant metric, I think, is number of lines that got un-indented (a high number is almost certainly going to be a good refactor, only 1-2 likely not).

That said, even (1) by itself would be an improvement I think (and certainly simpler), so perhaps it makes sense to just start there.
