### ISSUE TITLE
another opensource project, the famous vector db milvus,who use Revive

### ISSUE THREAD

**Issue by kerneltravel** [mgechev/revive#845]
refer to 
[milvus's Makefile](https://github.com/milvus-io/milvus/blob/4130b6dfc82a289b2899418f8a7c7dec9d589215/Makefile#L55C2-L55C2)
the famous vector db milvus is also using Revive for build.

**Comment by chavacava** [comment]
Hi @kerneltravel thanks for pointing milvus as `revive` user.
Feel free to open a PR to add it to the README file.
