### ISSUE TITLE
Revive process hangs on invalid recursive type

### ISSUE THREAD

**Issue by cordis-dev** [mgechev/revive#849]
**To Reproduce**
Given this source file:

```go
package p

type B[T any] interface {
	B /* ERROR "invalid recursive type" */ [*T]
}

type C[T any, U B[U]] interface {
	*T
}
```

Try to lint it using revive v1.3.2 (Windows):

```
revive.exe test.go
```

**Expected behavior**
Revive process should complete.

**Additional context**
Source file is taken from https://github.com/golang/go/blob/master/src/internal/types/testdata/fixedbugs/issue56665.go

**Comment by chavacava** [comment]
Hi @cordis-dev thanks for filling the issue. I'll take a look on it.

**Comment by denisvmedia** [comment]
I checked and the problem starts here:

```go
// check function encapsulates the call to go/types.Config.Check method and
// recovers if the called method panics (see issue #59)
func check(config *types.Config, n string, fset *token.FileSet, astFiles []*ast.File, info *types.Info) (p *types.Package, err error) {
	defer func() {
		if r := recover(); r != nil {
			err, _ = r.(error)
			p = nil
			return
		}
	}()

	return config.Check(n, fset, astFiles, info) // <=== here
}
```

Internally, it uses `types` built-in package, which then hangs in this function:

```go
// computeInterfaceTypeSet may be called with check == nil.
func computeInterfaceTypeSet(check *Checker, pos token.Pos, ityp *Interface) *_TypeSet {
```

And it seems to be a bug in go itself. Because you cannot compile this code (it also hangs):

```go
package main

type B[T any] interface {
    B /* ERROR "invalid recursive type" */ [*T]
}

type C[T any, U B[U]] interface {
    *T
}

func main() {
}
```

**Comment by denisvmedia** [comment]
Update: the problem was in go 1.19. But it's not a problem in go 1.20 (I didn't research on a particular commit/version where it was resolved), thus revive has to be built with a version after >= 1.20.

**Comment by chavacava** [comment]
Hi @denisvmedia, thanks for the update on this issue.
