### ISSUE TITLE
rule for redundant import aliases

### ISSUE THREAD

**Issue by damif94** [mgechev/revive#853]
**Is your feature request related to a problem? Please describe.**
In Goland IDE, I got errors for redundant import aliases, i.e., when the imported package name matches the alias names.
My coworkes at [draftea](https://www.draftea.com/) using VSCode don't get this errors, so it would be nice to make this compliant at the precommit/CI stage.

**Describe the solution you'd like**
A new rule `redundant-import-alias` that would warn upon this condition.

**Additional context**
The idea is to get this warning internalized into revive.

<img width="628" alt="Screen Shot 2023-07-29 at 17 40 02" src="https://github.com/mgechev/revive/assets/29461526/bd18a841-2300-4b81-9d84-8966bc6acd2d">

**Comment by damif94** [comment]
@chavacava now that the PR is merged, we need a new release right?

**Comment by chavacava** [comment]
The approach in `revive` is to use the master branch as the "latest version" of the tool.
Anyway, if for some reason a release is needed (for example if you are using `revive` through `golangci-lint`) @mgechev triggers a release  every ~4 months (or when critical bugs are fixed)

**Comment by damif94** [comment]
I think a release would be convenient so we can use it with github actions
https://github.com/morphy2k/revive-action/blob/master/Dockerfile#L4

**Comment by chavacava** [comment]
closed by #854
