### ISSUE TITLE
Suggestion to make a new release

### ISSUE THREAD

**Issue by denisvmedia** [mgechev/revive#877]
Can we have a new release? It's been a while since the last release. Also, the last release was compiled with go 1.19 (a bug in which as we discovered in #849 can cause freezes under certain circumstances). And go 1.19 is not supported anymore (1.20 and 1.21 a currently supported versions). Additionally, many of us use revive indirectly through `golangci-lint` that contains other linters and `golangci-lint` usually updates to only release versions of the linters it includes.

P.S. Sorry, for skipping the issue template, it all seemed to be irrelevant.

**Comment by mgechev** [comment]
Just pushed a tag v1.3.3 which will result in a new release.

No worries you skipped the issue template :)
