### ISSUE TITLE
Linter rule to check against import alias naming restrictions

### ISSUE THREAD

**Issue by denisvmedia** [mgechev/revive#880]
**Is your feature request related to a problem? Please describe.**

Go gives some recommendations on [how packages should be named](https://go.dev/blog/package-names). This should also imply the rules for the aliases. I'd like to check that aliases for packages in our project don't include CAPS and underscores.

**Describe the solution you'd like**
I have two options:

* Regex mask that would fit any possible extra limitations that the project might want to have (for example completely forbid `v1` alias)
* Add 2 configuration options: `forbidCAPS` and `forbidUnderscores`.

The first one is more universal, the second one is simpler and more precise. We can also combine both options but then it might bring confusion.

NB: in any case we'll skip `_` import alias used for side effects.

**Describe alternatives you've considered**
I checked `importas` linter and it didn't have this feature. I submitted a feature request there, but I'm not sure if it fits the idea of `importas`.

**Additional context**
Example:

```go
package foo

import (
    fooBAR "foo/bar" // MATCH /import alias should not include capital letters/
    bar_foo "bar/foo" // MATCH /import alias should not include underscores/
    _ "far/boo" // this is fine
)
```

OR

```go
package foo

import (
    foo_BAR "foo/bar" // MATCH /import alias must much the regular expression: "^[a-z][a-z0-9]{0,}$"/
    _ "far/boo" // this is fine
)
```

**Comment by chavacava** [comment]
Hi @denisvmedia, thanks for the proposal.
I think we could add the rule. By default, it only accepts `^[a-z]+$` or `_`  and optionally takes a regex as argument (that overwrites defaults)
What do you think?

**Comment by denisvmedia** [comment]
Works for me. I'd just extend the default regex to `^[a-z][a-z0-9]{0,}$` (which by default will allow digits in the name - sometimes it can be useful when importing multiple versions of one and the same package).

If you agree, I can start working on adding such a rule.

**Comment by chavacava** [comment]
Go @denisvmedia !
