### ISSUE TITLE
Add a rule to warn on explicit triggers of the garbage collector

### ISSUE THREAD

**Issue by chavacava** [mgechev/revive#89]
Calling `runtime.GC()` to force garbage collection is rarely a good idea. In very few occasions triggering the GC is justified (when benchmarking for example) but most of the time is a symptom of the developer trying (and failing) to be smarter than the runtime.

We can add a rule to warn on the presence of `runtime.GC()`

**Comment by mgechev** [comment]
This sounds reasonable to me.
