### ISSUE TITLE
"-include value" flag (analogous to "- exclude value")

### ISSUE THREAD

**Issue by damif94** [mgechev/revive#890]
**Is your feature request related to a problem? Please describe.**
Out projects are getting bigger and running revive withing precommit hook https://github.com/morphy2k/revive-action get's annoyingly slower.

**Describe the solution you'd like**
An -include flag with the following description:

```
  -include value
        list of globs which specify files to be included (incompatible with -exclude value)
```

The  https://github.com/morphy2k/revive-action pre-commit hook could then be updated (or other hooks) to analyze only the diff files only and hence be much faster.

-------

I can go on the PR, but first I would like your views @chavacava

**Comment by chavacava** [comment]
Hi @damif94 , thanks for the proposal. Right now I have restricted Internet access, I will check the ticket next week.
