### ISSUE TITLE
Supporting multiple expressions for import-alias-naming

### ISSUE THREAD

**Issue by denisvmedia** [mgechev/revive#924]
In my initial PR about adding [`import-alias-naming`](#881 ) we agreed to have only one expression. However, I'm now not able to easily solve the following limitation:

- allow all alphanumeric aliases with optional digits and have a length at least 1 symbol (i.e. `^[a-z][a-z0-9]*`)
- disallow `^v\d+$` aliases (e.g. `v1`)
- disallow `^v\d+alpha\d+$` aliases (e.g. `v1alpha1`)

In my PR I assumed that golang supports negative lookahead. Unfortunately, my assumption was wrong (as well as there's no support for positive lookahead, also in regex there's no general support for logical `AND`). Do you think, we can revise our decision and allow multiple rules that will be combined by logical `AND`? @chavacava 

I can submit a PR with an update (it will be backwards compatible).

**Comment by chavacava** [comment]
> Some people, when confronted with a problem, think “_I know, I'll use regular expressions._”   [Now they have two problems](http://regex.info/blog/2006-09-15/247).

**Comment by denisvmedia** [comment]
That's true, but considering there's no way to address the issue, should I submit a new PR? 😉

**Comment by chavacava** [comment]
@denisvmedia a PR will be welcome. Thank you!
