### ISSUE TITLE
replace directive error in latest tag / release

### ISSUE THREAD

**Issue by fcisnerosrojo** [mgechev/revive#958]
When i try to install the latest release i get an error:

go install github.com/mgechev/revive@latest

Output:
go: github.com/mgechev/revive@latest (in github.com/mgechev/revive@v1.3.5):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

**Comment by denisvmedia** [comment]
Duplicate #956
