### ISSUE TITLE
out-of-order rules in documentation

### ISSUE THREAD

**Issue by rittneje** [mgechev/revive#991]
https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md

error-naming, error-return, error-strings, and errorf are currently listed between empty-lines and enforce-map-style.

They should instead appear between enforce-slice-style and exported. (They are correct in the table of contents, but not the actual content.)

**Comment by chavacava** [comment]
Hi @rittneje , thanks for reporting the issue.
